version: '3'
services:
  app:
    container_name: "hugo-dash-ssg"
    image: gehno/hugo-dash
    build:
      context: .
      dockerfile: dockerfile
      target: deploy
    volumes:
       - ~/hugo/data:/src/data/
       - site:/src/public/
    # uncomment this lines out if you want to use the hugo webserver   
    #ports: 
    #  - 1313:1313

  nginx: 
      container_name: "hugo-dash-nginx"
      image: nginx:alpine
      volumes:
       - site:/usr/share/nginx/html:ro
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
      ports:
      - 8080:8080
volumes:
  site: